binance:
  endpoint: "https://api.binance.com"
  weight_limit: 1200
  request_queue:
    enabled: true
    max_parallel: 3
    cooldown_sec: 1.2
    backoff_policy: "exponential"
  websocket:
    enabled: true
    reconnect: true
    max_retries: 5

ratelimit:
  minute_limit:
    futures: 2400

permissions:
  - "futures_read"
  - "spot_read"