# 수집/분석 주기 및 품질 임계치, 보고서 옵션
collection:
  interval_min: 5
  window_min: 15
  symbols: ["BTCUSDT"]
  data_dir: "../data"
  state_file: "../state/state.json"

quality:
  partial_ok_threshold_pct: 5
  zscore_threshold: 4.0

report:
  enabled: true
  output_dir: "../reports"
  compress_gzip: true
  markdown: true